_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /{_locale}/_wdt
    requirements:
        _locale: en|fr|it|de

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /{_locale}/_profiler
    requirements:
        _locale: en|fr|it|de

_main:
    resource: routing.yml
