root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/
        permanent: true
        
app_sylius_product:
    resource: "@AppSyliusProductBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr

app_solr_search:
    resource: "@AppSolrSearchBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr
   
app_kit_site:
    resource: "@AppSiteBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr
        
kitpages_cms:
    resource: "@KitpagesCmsBundle/Resources/config/routing.yml"
    prefix: /{_locale}/administration/cms
    requirements:
        _locale: en|fr
        
kitpages_file:
    resource: "@KitpagesFileBundle/Resources/config/routing.yml"
    prefix: "file"

kitpages_cms_page_view_lang:
    pattern:  /{_locale}/cms/{id}/{urlTitle}
    defaults: { _controller: KitpagesCmsBundle:Page:view, _locale: en }
    requirements:
        id: \d+
        _locale: en|fr

sylius_web:
    resource: @SyliusWebBundle/Resources/config/routing/main.yml
    prefix: /{_locale}/
    requirements:
        _locale: en|fr

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/account/profile
    requirements:
        _locale: en|fr

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: en|fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: en|fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/account
    requirements:
        _locale: en|fr
        
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix: /{_locale}/administration
    requirements:
        _locale: en|fr
        