   
create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"
    
app_sylius_product:
    resource: "@AppSyliusProductBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|it|de
        
app_solr_search_main:
    resource: "@AppSolrSearchBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|it|de
   
app_kit_site:
    resource: "@AppSiteBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|it|de
        
kitpages_cms:
    resource: "@KitpagesCmsBundle/Resources/config/routing.yml"
    prefix: /{_locale}/administration/cms
    requirements:
        _locale: en|fr|it|de
        
kitpages_file:
    resource: "@KitpagesFileBundle/Resources/config/routing.yml"
    prefix: "file"

kitpages_cms_page_view_lang:
    pattern:  /{_locale}/cms/{id}/{urlTitle}
    defaults: { _controller: KitpagesCmsBundle:Page:view, _locale: en }

sylius_web:
    resource: @SyliusWebBundle/Resources/config/routing/main.yml
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|it|de

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|it|de

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|it|de

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
        
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/account/profile
    requirements:
        _locale: en|fr|it|de

fos_user_register:
    resource: "@AppUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: en|fr|it|de

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: en|fr|it|de

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/account
    requirements:
        _locale: en|fr|it|de
        
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix: /{_locale}/administration
    requirements:
        _locale: en|fr|it|de
        