root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/
        permanent: true
        
app_sylius_product:
    resource: "@AppSyliusProductBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr

app_solr_search_main:
    resource: "@AppSolrSearchBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr
   
app_kit_site:
    resource: "@AppSiteBundle/Resources/config/routing.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|fr

sylius_web:
    resource: @SyliusWebBundle/Resources/config/routing/main.yml
    prefix: /{_locale}/
    requirements:
        _locale: en|fr

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_register:
    resource: "@AppUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: en|fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: en|fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/account
    requirements:
        _locale: en|fr
        
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix: /{_locale}/administration
    requirements:
        _locale: en|fr
   

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login

amazon_login:
    path: /login/check-amazon

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

