   
create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"
    
app_sylius_product:
    resource: "@AppSyliusProductBundle/Resources/config/routing.yml"

app_solr_search_main:
    resource: "@AppSolrSearchBundle/Resources/config/routing.yml"
   
app_kit_site:
    resource: "@AppSiteBundle/Resources/config/routing.yml"
        
kitpages_cms:
    resource: "@KitpagesCmsBundle/Resources/config/routing.yml"
    prefix: /administration/cms
        
kitpages_file:
    resource: "@KitpagesFileBundle/Resources/config/routing.yml"
    prefix: "file"

kitpages_cms_page_view_lang:
    pattern:  /{_locale}/cms/{id}/{urlTitle}
    defaults: { _controller: KitpagesCmsBundle:Page:view, _locale: en }

sylius_web:
    resource: @SyliusWebBundle/Resources/config/routing/main.yml

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile

fos_user_register:
    resource: "@AppUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account
        
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix: /administration
        