# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_CMS_ADMIN,  ROLE_SYLIUS_ADMIN]
        ROLE_SUPERADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     fos_userbundle
                login_path:   /en/administration/login
                check_path:   /en/administration/login-check
                failure_path: /en/administration/login
                default_target_path: /en/administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /en/administration/logout
                target: /en/administration/login
            anonymous: true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*            
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                failure_path: null
                default_target_path: /
                use_forward:  false
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                login_path:   /connect
                failure_path: /connect
                oauth_user_provider:
                    service: sylius.oauth.user_provider
            logout: true
            anonymous: true
        checkout:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*            
            form_login:
                provider: fos_userbundle
                login_path: /en/checkout/security
                check_path: /login_check
                failure_path: null
                default_target_path: /
                use_forward:  false
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                login_path:   /connect
                failure_path: /connect
                oauth_user_provider:
                    service: sylius.oauth.user_provider
            logout: true
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/en/login, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/security.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/en/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        
        - { path: ^/en/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/administration/cms/block.*", role: ROLE_SYLIUS_ADMIN, requires_channel: http }
        - { path: ^/en/administration.*", role: ROLE_SYLIUS_ADMIN, requires_channel: https }

        - { path: ^/en/account.*, role: ROLE_USER, requires_channel: https }
        - { path: ^/en/cart.*, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/en/checkout.*, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: ^/fr/login, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/fr/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/fr/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: ^/fr/administration/cms/block.*", role: ROLE_SYLIUS_ADMIN, requires_channel: http }
        - { path: ^/fr/administration.*", role: ROLE_SYLIUS_ADMIN, requires_channel: https }

        - { path: ^/fr/account.*, role: ROLE_USER, requires_channel: https }
        - { path: ^/fr/cart.*, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/fr/checkout.*, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: "/_partial.*", ip: 127.0.0.1 }
