parameters:
  sylius.menu_builder.frontend.class: App\SyliusWebBundle\Menu\FrontendMenuBuilder
  sylius.menu_builder.backend.class: App\SyliusWebBundle\Menu\BackendMenuBuilder
  sylius.checkout_scenario.class: App\SyliusCoreBundle\Checkout\CheckoutProcessScenario
  sylius.checkout_step.security.class: App\SyliusCoreBundle\Checkout\Step\SecurityStep
  sylius.checkout_step.addressing.class: App\SyliusCoreBundle\Checkout\Step\AddressingStep
  sylius.checkout_step.shipping.class: App\SyliusCoreBundle\Checkout\Step\ShippingStep
  sylius.checkout_step.payment.class: App\SyliusCoreBundle\Checkout\Step\PaymentStep
  sylius.checkout_step.purchase.class: App\SyliusCoreBundle\Checkout\Step\PurchaseStep
  sylius.checkout_step.finalize.class: App\SyliusCoreBundle\Checkout\Step\FinalizeStep
  sylius.cart_item_resolver.default.class: App\SyliusCoreBundle\Cart\ItemResolver
  
         
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: App\SyliusProductBundle\Entity\Product
            form: App\SyliusProductBundle\Form\Type\ProductType
            repository: App\SyliusProductBundle\Entity\ProductRepository
            
sylius_variation:
    classes:
        product:
          variant:
              model: App\SyliusProductBundle\Entity\ProductVariant
              form: App\SyliusProductBundle\Form\Type\ProductVariantType

sylius_cart:
    classes:
        item:
            controller: App\CartBundle\Controller\CartItemController

sylius_inventory:
    backorders: false
    track_inventory: true