parameters:
  sylius.menu_builder.frontend.class: App\SyliusWebBundle\Menu\FrontendMenuBuilder
  sylius.menu_builder.backend.class: App\SyliusWebBundle\Menu\BackendMenuBuilder
  sylius.checkout_scenario.class: App\SyliusCoreBundle\Checkout\CheckoutProcessScenario
  sylius.checkout_step.security.class: App\SyliusCoreBundle\Checkout\Step\SecurityStep
  sylius.checkout_step.addressing.class: App\SyliusCoreBundle\Checkout\Step\AddressingStep
  sylius.checkout_step.purchase.class: App\SyliusCoreBundle\Checkout\Step\PurchaseStep
  sylius.checkout_step.finalize.class: App\SyliusCoreBundle\Checkout\Step\FinalizeStep
  sylius.cart_item_resolver.default.class: App\SyliusCoreBundle\Cart\ItemResolver
        
  
sylius_core:
    emails:
        enabled: true
        from_email:
            address: %emails.address%
            sender_name: 'Italica Shop'            
          
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: App\SyliusProductBundle\Entity\Product
            form: App\SyliusProductBundle\Form\Type\ProductType
            repository: App\SyliusProductBundle\Entity\ProductRepository
            
sylius_variation:
    classes:
        product:
          variant:
              model: App\SyliusProductBundle\Entity\ProductVariant
              form: App\SyliusProductBundle\Form\Type\ProductVariantType

sylius_cart:
    classes:
        item:
            controller: App\CartBundle\Controller\CartItemController

sylius_inventory:
    backorders: false
    track_inventory: true
    
sylius_payment:
    classes:
        payment:
            model: Sylius\Component\Core\Model\Payment
            controller: Sylius\Bundle\CoreBundle\Controller\PaymentController
    gateways:
        postpay: Postpay
        
payum:
    storages:
        Sylius\Component\Core\Model\Order: { doctrine: orm }
        Sylius\Component\Core\Model\Payment: { doctrine: orm }

    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }

    contexts:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox:   %paypal.express_checkout.sandbox%

        stripe:
            omnipay:
                type: Stripe
                options:
                    apiKey:   %stripe.secret_key%
                    testMode: %stripe.test_mode%

        be2bill:
            be2bill:
                identifier: %be2bill.identifier%
                password:   %be2bill.password%
                sandbox:    %be2bill.sandbox%

        be2bill_onsite:
            be2bill_onsite:
                identifier: %be2bill.identifier%
                password:   %be2bill.password%
                sandbox:    %be2bill.sandbox%
                    
        dummy:
            custom:
                actions:
                    - sylius.payum.dummy.action.capture_payment
                    - sylius.payum.dummy.action.payment_status
                    
        postpay:
            custom:
                actions:
                    - sylius.payum.postpay.action.capture_payment
                    - sylius.payum.postpay.action.payment_status