<?php

namespace App\SolrSearchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacetLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacetLogRepository extends EntityRepository
{
}
