<?php

namespace App\SolrSearchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchLogRepository extends EntityRepository
{
}
