app_site_brand:
    pattern:  /brands
    defaults: { _controller: AppSiteBundle:Site:brandList }
    
app_postpay_template:
    pattern:  /payment/postpay
    defaults: { _controller: AppSiteBundle:Payment:postpayTemplate }
        
app_site_subscription:
    pattern:  /subscription
    defaults: { _controller: AppSiteBundle:Site:subscription }
        
app_site_subscription_list:
    pattern:  /administration/subscription/list
    defaults: { _controller: AppSiteBundle:Subscription:getSubscriptionsList }
    
app_site_subscription_delete:
    pattern:  /administration/subscription/delete/{id}
    defaults: { _controller: AppSiteBundle:Subscription:deleteSubscription }
    
app_site_sitemap:
    pattern:  /sitemap.xml
    defaults: { _controller: AppSiteBundle:Sitemap:xmlSitemap }
    
app_site_sitemap_site:
    pattern:  /sitemap
    defaults: { _controller: AppSiteBundle:Sitemap:sitemap }
    
app_site_sitemap_site:
    pattern:  /info/{key}
    defaults: { _controller: AppSiteBundle:Site:page }
    requirements:
        key: delivery|privacy-policy|faq|terms-conditions|returns-refunds|contact-us
        
app_site_export:
    pattern:  /export
    defaults: { _controller: AppSiteBundle:Site:export }

