default:
    pattern:  /
    defaults: { _controller: AppSiteBundle:Site:index }
    
app_site_brand:
    pattern:  /{_locale}/brands
    defaults: { _controller: AppSiteBundle:Site:brandList }
    requirements:
        _locale: en|fr
        
app_site_newsletter:
    pattern:  /{_locale}/newsletter
    defaults: { _controller: AppSiteBundle:Site:subscription }
    requirements:
        _locale: en|fr
