services:
    app.repository.subscription:
        class: App\SiteBundle\Entity\SubscriptionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - App\SiteBundle\Entity\Subscription
            
    site.twig.extension:
        class: App\SiteBundle\Extension\TwigExtension
        tags:
            -  { name: twig.extension }
            
    app.locale_listener:
        class: App\SiteBundle\EventListener\LocaleListener
        arguments: ["@sylius.context.locale"]
        tags:
            - { name: kernel.event_subscriber }