services:
    app.repository.subscription:
        class: App\SiteBundle\Entity\SubscriptionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - App\SiteBundle\Entity\Subscription