services:
    sylius.repository.product.group:
        class: App\SyliusProductBundle\Entity\ProductGroupRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - App\SyliusProductBundle\Entity\ProductGroup
            
    sylius.repository.product_size_guide:
        class: App\SyliusProductBundle\Entity\ProductSizeGuideRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - App\SyliusProductBundle\Entity\ProductSizeGuide
            
    sylius.repository.product_dropship:
        class: App\SyliusProductBundle\Entity\ProductDropshipRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - App\SyliusProductBundle\Entity\ProductDropship
