<?php

namespace App\SyliusProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLogRepository extends EntityRepository
{
}
