<?php

namespace App\SyliusProductBundle\Entity;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;


/**
 * ProductSizeGuideFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSizeGuideFieldRepository extends EntityRepository
{
}
